cursor #ede0d4
cursor_text_color #d3c4b4

foreground            #ede0d4
background            #18120c
selection_foreground  #3f2d16
selection_background  #dec2a2
url_color             #f6bc70

color0   #18120c
color1   #ff7066
color2   #85f670
color3   #ffe466
color4   #e9a750
color5   #714000
color6   #f6bc70
color7   #fff7ee
color8   #9f9a92
color9   #ff9d96
color10  #adff9d
color11  #ffee9d
color12  #ffcb88
color13  #ffd49d
color14  #ffe3c0
color15  #fffbf8
