cursor #ebe1d4
cursor_text_color #d1c5b4

foreground            #ebe1d4
background            #17130b
selection_foreground  #3b2f15
selection_background  #d8c4a0
url_color             #eac16c

color0   #17130b
color1   #ff7467
color2   #7eea6c
color3   #ffe567
color4   #deaf4e
color5   #6c4901
color6   #eac16c
color7   #f5f0e5
color8   #98948b
color9   #ffa098
color10  #adff9e
color11  #ffee9e
color12  #ffd98a
color13  #ffdf9e
color14  #ffeac1
color15  #fffcf8
