cursor #f0dedf
cursor_text_color #d7c1c3

foreground            #f0dedf
background            #1a1112
selection_foreground  #43292d
selection_background  #e5bdc1
url_color             #ffb2bc

color0   #1a1112
color1   #ff7274
color2   #9cff7f
color3   #ffe372
color4   #f29aa5
color5   #76343d
color6   #ffb2bc
color7   #ffeff1
color8   #494041
color9   #ff9fa0
color10  #baffa5
color11  #ffeda5
color12  #ffbdc6
color13  #ffc9d0
color14  #ffdce0
color15  #fff8f9
