[colors.primary]
background = '#191114'
foreground = '#efdfe2'

[colors.selection]
text = '#efdfe2'
background = '#6f334a'

[colors.cursor]
text = '#191114'
cursor = '#ffb0ca'

[colors.normal]
black   = '#191114'
red     = '#ff7278'
green   = '#9fff7f'
yellow  = '#ffe272'
blue    = '#f298b5'
magenta = '#763249'
cyan    = '#ffb0ca'
white   = '#ffeff4'

[colors.bright]
black   = '#484043'
red     = '#ff9fa3'
green   = '#bcffa5'
yellow  = '#ffeca5'
blue    = '#ffbbd1'
magenta = '#ffc7d9'
cyan    = '#ffdbe7'
white   = '#fff8fa'
