[colors.primary]
background = '#1a1112'
foreground = '#f0dedf'

[colors.selection]
text = '#f0dedf'
background = '#72333e'

[colors.cursor]
text = '#1a1112'
cursor = '#ffb2bc'

[colors.normal]
black   = '#1a1112'
red     = '#ff7274'
green   = '#9cff7f'
yellow  = '#ffe372'
blue    = '#f29aa5'
magenta = '#76343d'
cyan    = '#ffb2bc'
white   = '#ffeff1'

[colors.bright]
black   = '#494041'
red     = '#ff9fa0'
green   = '#baffa5'
yellow  = '#ffeda5'
blue    = '#ffbdc6'
magenta = '#ffc9d0'
cyan    = '#ffdce0'
white   = '#fff8f9'
