[colors.primary]
background = '#141318'
foreground = '#e6e1e9'

[colors.selection]
text = '#e6e1e9'
background = '#4b3e76'

[colors.cursor]
text = '#141318'
cursor = '#cdbdff'

[colors.normal]
black   = '#141318'
red     = '#ff7290'
green   = '#7fff99'
yellow  = '#ffd972'
blue    = '#b9a7f2'
magenta = '#4b3e76'
cyan    = '#cdbdff'
white   = '#f3efff'

[colors.bright]
black   = '#43414a'
red     = '#ff9fb3'
green   = '#a5ffb8'
yellow  = '#ffe7a5'
blue    = '#d4c6ff'
magenta = '#dbd0ff'
cyan    = '#e8e1ff'
white   = '#faf8ff'
